# On each change here, update variable 'cacheImageVersion' in jenkinsfile/build.groovy
#FROM hseeberger/scala-sbt:8u212_1.2.8_2.13.0
#FROM sbtscala/scala-sbt:eclipse-temurin-alpine-22_36_1.10.0_3.4.2
# FROM sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.2_13_1.10.0_3.4.2
FROM sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.10.0_3.4.2
LABEL version="1.0"

WORKDIR /workspace
COPY build.sbt ./build.sbt
COPY project ./project
RUN sbt update
