version: "3.3"
services:
  kalinka:
    build: .
    links:
      - postgres
    ports:
      - "9003:9000"
    environment:
      - "APPLICATION_SECRET=${APPLICATION_SECRET}"
      - "DATABASE_HOST=postgres"
      - "DATABASE_PORT=5432"
      - "DATABASE_NAME=kalinka"
      - "DATABASE_USER=${DATABASE_USER}"
      - "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
      - "KALINKA_HOST=dona.dev.mbp.tf.uni-bielefeld.de"
      - "SOCIAL_DATA_SOURCE_ID=1234566"
      - "SOCIAL_DATA_INGESTION_ENABLED=on"
      - "DONOR_SURVEY_ENABLED=off"
      - "DONOR_SURVEY_LINK=https://survey.mbp.tf.uni-bielefeld.de/index.php?r=survey/index&sid=387762&newtest=Y"
      - "FEEDBACK_SURVEY_LINK=https://survey.mbp.tf.uni-bielefeld.de/index.php?r=survey/index&sid=887296&newtest=Y"
      - "SECURE_COOKIE=false"
  postgres:
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "kalinka"
    image: postgres:12
    volumes:
      - improvements_dev_dona_data:/var/lib/postgresql/data
    ports:
      - "5558:5432"
volumes:
  improvements_dev_dona_data:
