version: "3.3"
services:
  kalinka:
    restart: unless-stopped
    build: .
    links:
      - postgres
    ports:
      - "9010:9000"
    environment:
      - "APPLICATION_SECRET=${APPLICATION_SECRET}"
      - "DATABASE_HOST=postgres"
      - "DATABASE_PORT=5432"
      - "DATABASE_NAME=kalinka"
      - "DATABASE_USER=${DATABASE_USER}"
      - "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
      - "KALINKA_HOST=dona.tf.uni-bielefeld.de"
      - "SOCIAL_DATA_SOURCE_ID=1234566"
      - "SOCIAL_DATA_INGESTION_ENABLED=on"
      - "DONOR_SURVEY_ENABLED=on"
      - "DONOR_SURVEY_LINK=https://survey.mbp.tf.uni-bielefeld.de/index.php?r=survey/index&sid=227434&newtest=Y"
      - "FEEDBACK_SURVEY_LINK=https://survey.mbp.tf.uni-bielefeld.de/index.php?r=survey/index&sid=738444"
      - "SECURE_COOKIE=false"
      - "DONOR_ID_INPUT_METHOD=default"
  postgres:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "kalinka"
    image: postgres:12
    volumes:
      - project05:/var/lib/postgresql/data
    ports:
      - "5565:5432"
volumes:
  project05:
