KALINKA_HOST: socialdata.hpsgc.de
KALINKA_DB_CONFIGMAP: kalinka-db-connection
KALINKA_DB_CREDS_SECRET_NAME: kalinka-db-credentials
KALINKA_PORT: 9000
DONOR_SURVEY_ENABLED: true
DONOR_SURVEY_LINK: https://www.soscisurvey.de/dona/
SOCIAL_DATA_INGESTION_ENABLED: true
IMAGE_REPOSITORY: alp-snapshots.hpsgc.de/
NUM_REPLICAS: 3
